### ISSUE TITLE
Import of FNO failed 

### ISSUE THREAD

**Issue by MaAl13** [neuraloperator/neuraloperator#126]
When i try to run the basic code to import FNO, i get the following error:

`from neuralop.models import FNO`

ImportError                               Traceback (most recent call last)
[<ipython-input-28-4c623c2d0de3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from neuralop.models import FNO
      2 
      3 operator = FNO(n_modes=(16,), hidden_channels=64,
      4                 in_channels=1, out_channels=1)

ImportError: cannot import name 'FNO' from 'neuralop.models' (/usr/local/lib/python3.9/dist-packages/neuralop/models/__init__.py)

**Comment by JeanKossaifi** [comment]
Can you print `neuralop.__version__`?

**Comment by MaAl13** [comment]
I have version 0.1.1 according to the command.

**Comment by MaxGhi8** [comment]
Maybe the issue is due to that there isn't a file called FNO in neuralop.models (i'm not very sure about that)... But if you try to run the second block of code (with tfno) it works because there is a file called TFNO in neuralop.models. To try this code make sure to add a "," before the last line of code. Also make sure to have all the requirments package installed, you can watch this in the requirments.txt file.

**Comment by JeanKossaifi** [comment]
@MaAl13 can you try updating to the last version and see if that fixes your issue?

**Comment by JeanKossaifi** [comment]
Closing as inactive, feel free to reopen if updating hasn't fixed your issue.
