### ISSUE TITLE
fourier_3d code question

### ISSUE THREAD

**Issue by zmqkf73** [neuraloperator/neuraloperator#132]
Hi,
I'm looking at the fourier_3d code and I can see the expanding dimension of train_a and test_a using reshape function.
Why expand the dimension of those data?
And most recently updated code, I can't see this expanding part. 
Doesn't it matter?

**Comment by MaxGhi8** [comment]
Hi, I think it is useful to expand the size of a_train and a_test because in the forward method of the FNO3d class, the uniform grid is calculated and attached as features together with the evaluations of a. So expanding the dimensions becomes convenient so you can do torch.cat. Attaching the grid together with a as input should also be convenient to achieve better performance (I think). The same process is also done in fourier_2d and perhaps there are fewer dimensions there and it is easy to see what is happening.
