### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by mshmoon** [neuraloperator/neuraloperator#433]
Firstly, thank you very much for your work. But I found a problem while studying your repo, I cannot understand the input and output of each model and how to input the grid into the model, especially Gino. So I think it might be better to have a data processing process for others to learn from. Thank you

**Comment by dhpitt** [comment]
Hi @mshmoon, thank you for this feedback. This is really good to know from a user! Since last month we've made some updates to the GINO model including the docstring which should simplify things somewhat. But stay tuned for updates this month - we're planning to add a training recipe for the GINO which should help clear things up.

**Comment by dhpitt** [comment]
@mshmoon  - you can check `scripts/train_gino_carcfd.py` for an example!

**Comment by JeanKossaifi** [comment]
Closing as answered - feel free to reopen if you have more questions.
