### ISSUE TITLE
pip install dependencies are not working 

### ISSUE THREAD

**Issue by esl-lewis** [neuraloperator/neuraloperator#439]
Installing from pip and running `import neuralop` returns the following error `ModuleNotFoundError: No module named 'torch_harmonics'` for both Python 3.9 and 3.10

**Comment by dhpitt** [comment]
Hi @esl-lewis , thanks for raising this issue. It has been a long time since the last pip release, and we currently recommend building the library from source. We are planning a new pip release soon that will fix these dependency issues, but for the meantime, please check out the `Installation` section in the library's README.

**Comment by esl-lewis** [comment]
Thank you for the quick feedback, for future reference attempting to build from source also throws an issue with the `torch_harmonics` (0.7.1) dependency. But explicitly installing the previous version of that package (0.6) does work
